"""Unit tests for the SCD Type 2 pipeline (04.scd_genie_code_pipeline.py).

The pipeline is generated by Databricks Genie and uses the Databricks-specific
``create_auto_cdc_flow`` API (unavailable in open-source PySpark). Tests verify
the pipeline structure, module-level constants, and the exact arguments forwarded
to both ``create_streaming_table`` and ``create_auto_cdc_flow``.
"""

import importlib.util
from pathlib import Path
from unittest.mock import MagicMock, patch

import pyspark.pipelines as dp_mod
import pytest
from pyspark.pipelines.output import StreamingTable

# ---------------------------------------------------------------------------
# Module loader
# ---------------------------------------------------------------------------

_PIPELINE_PATH = Path(__file__).parent.parent / "src/python/notebooks/04.scd_genie_code_pipeline.py"


def _load_pipeline_module():
    """Load the SCD pipeline module directly from its file path."""
    spec = importlib.util.spec_from_file_location("scd_pipeline", _PIPELINE_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_PIPELINE = _load_pipeline_module()

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_cdc():
    """Patch create_auto_cdc_flow (Databricks-only) onto the pyspark.pipelines module."""
    with patch.object(dp_mod, "create_auto_cdc_flow", MagicMock(), create=True) as m:
        yield m


# ---------------------------------------------------------------------------
# Tests: module-level constants
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("attr", "expected"),
    [
        ("SOURCE_TABLE", "test_catalog.test_silver_schema.fake_orders_staging"),
        ("TARGET_CATALOG", "test_catalog"),
        ("GOLD_SCHEMA", "test_gold_schema"),
        ("TARGET_TABLE_NAME", "fake_orders_scd2"),
        ("KEY_COLUMN", "id"),
        ("SEQUENCE_COLUMN", "timestamp"),
        ("HISTORY_TRACKED_COLUMNS", ["productid", "userid"]),
    ],
)
def test_pipeline_constant(attr: str, expected: object) -> None:
    """Should expose each module-level constant with the expected value."""
    assert getattr(_PIPELINE, attr) == expected


# ---------------------------------------------------------------------------
# Tests: target table name construction
# ---------------------------------------------------------------------------


def test_target_table_full_name() -> None:
    """Should assemble a valid three-part catalog.schema.table name from the module constants."""
    expected = "test_catalog.test_gold_schema.fake_orders_scd2"
    actual = f"{_PIPELINE.TARGET_CATALOG}.{_PIPELINE.GOLD_SCHEMA}.{_PIPELINE.TARGET_TABLE_NAME}"
    assert actual == expected


# ---------------------------------------------------------------------------
# Tests: create_streaming_table registration
# ---------------------------------------------------------------------------


def test_registers_one_streaming_table(registry, mock_cdc) -> None:
    """Should register exactly one StreamingTable output."""
    _PIPELINE.create_orders_scd2_table()

    st_outputs = [o for o in registry.outputs if isinstance(o, StreamingTable)]
    assert len(st_outputs) == 1


def test_streaming_table_has_correct_name(registry, mock_cdc) -> None:
    """Should register the streaming table with the fully-qualified target name."""
    _PIPELINE.create_orders_scd2_table()

    st = next(o for o in registry.outputs if isinstance(o, StreamingTable))
    assert st.name == "test_catalog.test_gold_schema.fake_orders_scd2"


def test_streaming_table_has_comment(registry, mock_cdc) -> None:
    """Should attach a non-empty descriptive comment to the streaming table."""
    _PIPELINE.create_orders_scd2_table()

    st = next(o for o in registry.outputs if isinstance(o, StreamingTable))
    assert st.comment is not None
    assert len(st.comment) > 0


def test_no_extra_outputs_registered(registry, mock_cdc) -> None:
    """Should register no outputs beyond the single SCD2 streaming table."""
    _PIPELINE.create_orders_scd2_table()

    assert len(registry.outputs) == 1


def test_no_flows_registered_in_registry(registry, mock_cdc) -> None:
    """Should not register any flows — CDC flow is handled outside the registry."""
    _PIPELINE.create_orders_scd2_table()

    assert len(registry.flows) == 0


# ---------------------------------------------------------------------------
# Tests: create_auto_cdc_flow invocation
# ---------------------------------------------------------------------------


def test_cdc_flow_is_called_once(registry, mock_cdc) -> None:
    """Should invoke create_auto_cdc_flow exactly once per pipeline run."""
    _PIPELINE.create_orders_scd2_table()

    assert mock_cdc.call_count == 1


@pytest.mark.parametrize(
    ("kwarg", "expected"),
    [
        ("target", "test_catalog.test_gold_schema.fake_orders_scd2"),
        ("source", "test_catalog.test_silver_schema.fake_orders_staging"),
        ("keys", ["id"]),
        ("sequence_by", "timestamp"),
        ("stored_as_scd_type", 2),
        ("track_history_column_list", ["productid", "userid"]),
        ("ignore_null_updates", True),
    ],
)
def test_cdc_flow_kwarg(registry, mock_cdc, kwarg: str, expected: object) -> None:
    """Should forward each expected keyword argument to create_auto_cdc_flow."""
    _PIPELINE.create_orders_scd2_table()

    assert mock_cdc.call_args.kwargs[kwarg] == expected
