"""Unit tests for the SCD Type 2 pipeline (04.scd_genie_code_pipeline.py).

The pipeline is generated by Databricks Genie and uses the Databricks-specific
``create_auto_cdc_flow`` API (unavailable in open-source PySpark). Tests verify
the pipeline structure, module-level constants, and the exact arguments forwarded
to both ``create_streaming_table`` and ``create_auto_cdc_flow``.
"""

import importlib.util
from pathlib import Path
from unittest.mock import MagicMock, patch

import pyspark.pipelines as dp_mod
import pytest
from pyspark.pipelines.flow import Flow
from pyspark.pipelines.graph_element_registry import (
    GraphElementRegistry,
    graph_element_registration_context,
)
from pyspark.pipelines.output import Output, StreamingTable

# ---------------------------------------------------------------------------
# Module loader
# ---------------------------------------------------------------------------

_PIPELINE_PATH = Path(__file__).parent.parent / "04.scd_genie_code_pipeline.py"


def _load_pipeline_module():
    """Load the SCD pipeline module directly from its file path."""
    spec = importlib.util.spec_from_file_location("scd_pipeline", _PIPELINE_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_PIPELINE = _load_pipeline_module()

# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------


class MockGraphElementRegistry(GraphElementRegistry):
    """Collects all outputs and flows registered during a pipeline definition."""

    def __init__(self):
        self.outputs: list[Output] = []
        self.flows: list[Flow] = []

    def register_output(self, output: Output) -> None:
        """Record an output in the mock registry."""
        self.outputs.append(output)

    def register_flow(self, flow: Flow) -> None:
        """Record a flow in the mock registry."""
        self.flows.append(flow)

    def register_sql(self, sql_text: str, file_path: Path) -> None:
        """No-op: SQL registration is not needed for Python-only tests."""


@pytest.fixture
def registry():
    """Provide a fresh MockGraphElementRegistry inside a registration context."""
    reg = MockGraphElementRegistry()
    with graph_element_registration_context(reg):
        yield reg


@pytest.fixture
def mock_cdc():
    """Patch create_auto_cdc_flow (Databricks-only) onto the pyspark.pipelines module."""
    with patch.object(dp_mod, "create_auto_cdc_flow", MagicMock(), create=True) as m:
        yield m


# ---------------------------------------------------------------------------
# Tests: module-level constants
# ---------------------------------------------------------------------------


class TestPipelineConstants:
    """Tests that pipeline configuration constants are set to the expected values."""

    def test_source_table(self):
        """Should reference the silver-layer staging table as the CDC source."""
        assert _PIPELINE.SOURCE_TABLE == "test_catalog.test_silver_schema.fake_orders_staging"

    def test_target_catalog(self):
        """Should use test_catalog as the target catalog."""
        assert _PIPELINE.TARGET_CATALOG == "test_catalog"

    def test_gold_schema(self):
        """Should use the gold schema for the output table."""
        assert _PIPELINE.GOLD_SCHEMA == "test_gold_schema"

    def test_target_table_name(self):
        """Should name the target table fake_orders_scd2."""
        assert _PIPELINE.TARGET_TABLE_NAME == "fake_orders_scd2"

    def test_key_column(self):
        """Should use 'id' as the primary key column."""
        assert _PIPELINE.KEY_COLUMN == "id"

    def test_sequence_column(self):
        """Should use 'timestamp' as the sequencing column for CDC ordering."""
        assert _PIPELINE.SEQUENCE_COLUMN == "timestamp"

    def test_history_tracked_columns(self):
        """Should track history only for the 'productid' column."""
        assert _PIPELINE.HISTORY_TRACKED_COLUMNS == ["productid"]


# ---------------------------------------------------------------------------
# Tests: target table name construction
# ---------------------------------------------------------------------------


class TestTargetTableName:
    """Tests that the fully-qualified target table name is assembled correctly."""

    def test_full_table_name(self):
        """Should produce a three-part catalog.schema.table name."""
        expected = "test_catalog.test_gold_schema.fake_orders_scd2"
        actual = f"{_PIPELINE.TARGET_CATALOG}.{_PIPELINE.GOLD_SCHEMA}.{_PIPELINE.TARGET_TABLE_NAME}"
        assert actual == expected

    def test_table_name_has_three_parts(self):
        """Should contain exactly three dot-separated segments."""
        full_name = (
            f"{_PIPELINE.TARGET_CATALOG}.{_PIPELINE.GOLD_SCHEMA}.{_PIPELINE.TARGET_TABLE_NAME}"
        )
        assert len(full_name.split(".")) == 3

    def test_source_table_references_silver_schema(self):
        """Should read from silver_schema, not bronze or gold."""
        assert "silver_schema" in _PIPELINE.SOURCE_TABLE

    def test_target_references_gold_schema(self):
        """Should write to gold_schema."""
        full_name = (
            f"{_PIPELINE.TARGET_CATALOG}.{_PIPELINE.GOLD_SCHEMA}.{_PIPELINE.TARGET_TABLE_NAME}"
        )
        assert "gold_schema" in full_name


# ---------------------------------------------------------------------------
# Tests: create_streaming_table registration
# ---------------------------------------------------------------------------


class TestCreateStreamingTableRegistration:
    """Tests that create_orders_scd2_table registers a StreamingTable correctly."""

    def test_registers_one_streaming_table(self, registry, mock_cdc):
        """Should register exactly one StreamingTable output."""
        _PIPELINE.create_orders_scd2_table()

        st_outputs = [o for o in registry.outputs if isinstance(o, StreamingTable)]
        assert len(st_outputs) == 1

    def test_streaming_table_has_correct_name(self, registry, mock_cdc):
        """Should register the streaming table with the fully-qualified target name."""
        _PIPELINE.create_orders_scd2_table()

        st = next(o for o in registry.outputs if isinstance(o, StreamingTable))
        assert st.name == "test_catalog.test_gold_schema.fake_orders_scd2"

    def test_streaming_table_has_comment(self, registry, mock_cdc):
        """Should attach a non-empty descriptive comment to the streaming table."""
        _PIPELINE.create_orders_scd2_table()

        st = next(o for o in registry.outputs if isinstance(o, StreamingTable))
        assert st.comment is not None
        assert len(st.comment) > 0

    def test_no_extra_outputs_registered(self, registry, mock_cdc):
        """Should register no outputs beyond the single SCD2 streaming table."""
        _PIPELINE.create_orders_scd2_table()

        assert len(registry.outputs) == 1

    def test_no_flows_registered_in_registry(self, registry, mock_cdc):
        """Should not register any flows — CDC flow is handled outside the registry."""
        _PIPELINE.create_orders_scd2_table()

        assert len(registry.flows) == 0


# ---------------------------------------------------------------------------
# Tests: create_auto_cdc_flow invocation
# ---------------------------------------------------------------------------


class TestCreateAutoCdcFlowInvocation:
    """Tests that create_auto_cdc_flow is called with the correct arguments."""

    def test_cdc_flow_is_called_once(self, registry, mock_cdc):
        """Should invoke create_auto_cdc_flow exactly once per pipeline run."""
        _PIPELINE.create_orders_scd2_table()

        assert mock_cdc.call_count == 1

    def test_cdc_flow_target_matches_streaming_table(self, registry, mock_cdc):
        """Should pass the same fully-qualified name as both the table and CDC target."""
        _PIPELINE.create_orders_scd2_table()

        assert (
            mock_cdc.call_args.kwargs["target"] == "test_catalog.test_gold_schema.fake_orders_scd2"
        )

    def test_cdc_flow_source_is_staging_table(self, registry, mock_cdc):
        """Should read from the silver staging table."""
        _PIPELINE.create_orders_scd2_table()

        assert (
            mock_cdc.call_args.kwargs["source"]
            == "test_catalog.test_silver_schema.fake_orders_staging"
        )

    def test_cdc_flow_keys_contain_id(self, registry, mock_cdc):
        """Should use 'id' as the CDC primary key."""
        _PIPELINE.create_orders_scd2_table()

        assert mock_cdc.call_args.kwargs["keys"] == ["id"]

    def test_cdc_flow_sequence_by_is_timestamp(self, registry, mock_cdc):
        """Should sequence CDC events by the 'timestamp' column."""
        _PIPELINE.create_orders_scd2_table()

        assert mock_cdc.call_args.kwargs["sequence_by"] == "timestamp"

    def test_cdc_flow_stored_as_scd_type_2(self, registry, mock_cdc):
        """Should store as SCD Type 2 to preserve full product change history."""
        _PIPELINE.create_orders_scd2_table()

        assert mock_cdc.call_args.kwargs["stored_as_scd_type"] == 2

    def test_cdc_flow_tracks_productid_history(self, registry, mock_cdc):
        """Should limit history tracking to the 'productid' column."""
        _PIPELINE.create_orders_scd2_table()

        assert mock_cdc.call_args.kwargs["track_history_column_list"] == ["productid"]

    def test_cdc_flow_ignores_null_updates(self, registry, mock_cdc):
        """Should set ignore_null_updates=True to avoid overwriting existing data with nulls."""
        _PIPELINE.create_orders_scd2_table()

        assert mock_cdc.call_args.kwargs["ignore_null_updates"] is True
